"""
OrbitMesh telemetry parser.

Decodes telemetry packets generated by the OrbitMesh
telemetry service.

Author:
    OrbitMesh Contributors

License:
    Apache License 2.0
"""

from __future__ import annotations

import argparse
import struct
import sys


HEALTH_STATUS = {
    0: "OK",
    1: "WARNING",
    2: "ERROR",
}


TELEMETRY_HEADER_SIZE = 8


def parse_packet(
    data: bytes,
) -> dict[str, int | str]:
    """
    Parse an OrbitMesh telemetry payload.

    Payload format:

    Bytes 0-3:
        heartbeat counter

    Bytes 4-7:
        fault counter

    Byte 8:
        health status
    """

    if len(data) < 9:
        raise ValueError(
            "Telemetry packet too short"
        )


    heartbeat = struct.unpack(
        "<I",
        data[0:4],
    )[0]


    faults = struct.unpack(
        "<I",
        data[4:8],
    )[0]


    status = HEALTH_STATUS.get(
        data[8],
        "UNKNOWN",
    )


    return {
        "heartbeat": heartbeat,
        "faults": faults,
        "health": status,
    }



def parse_hex(
    value: str,
) -> bytes:
    """
    Convert hexadecimal input into bytes.
    """

    try:
        return bytes.fromhex(value)

    except ValueError as error:
        raise ValueError(
            "Invalid hexadecimal data"
        ) from error



def create_parser() -> argparse.ArgumentParser:
    """
    Create command line parser.
    """

    parser = argparse.ArgumentParser(
        description="OrbitMesh telemetry parser"
    )

    parser.add_argument(
        "packet",
        help="Telemetry packet as hexadecimal bytes",
    )

    return parser



def main() -> None:
    """
    Command line entry point.
    """

    parser = create_parser()

    args = parser.parse_args()


    try:
        packet = parse_hex(
            args.packet
        )

        result = parse_packet(
            packet
        )

    except ValueError as error:
        print(
            error,
            file=sys.stderr,
        )

        sys.exit(1)


    print(
        "OrbitMesh Telemetry"
    )

    print(
        f"Heartbeat: {result['heartbeat']}"
    )

    print(
        f"Faults: {result['faults']}"
    )

    print(
        f"Health: {result['health']}"
    )


if __name__ == "__main__":
    main()
