#
# OrbitMesh Examples
#
# Builds example applications.
#
# License:
# Apache License 2.0
#


add_subdirectory(
    basic_satellite
)

add_subdirectory(
    blinky
)


add_subdirectory(
    uart_echo
)


add_subdirectory(
    heartbeat
)


add_subdirectory(
    telemetry
)


add_subdirectory(
    sensor_polling
)
